const cards = [
  {name:'2 of Clubs' , value:2 , img: '2C.png'},
  {name:'2 of Diamonds' , value:2 , img: '2D.png'},
  {name:'2 of Spades' , value:2, img: '2S.png'},
  {name:'2 of Hearts' , value:2 , img: '2H.png'},
  {name:'3 of Clubs' , value:3 , img: '.3Cpng'},
  {name:'3 of Diamonds' , value:3 , img: '3D.png'},
  {name:'3 of Spades' , value:3 , img: '3S.png'},
  {name:'3 of Hearts' , value:3 , img: '3H.png'},
  {name:'4 of Clubs' , value:4 , img: '4C.png'},
  {name:'4 of Diamonds' , value:4 , img: '4D.png'},
  {name:'4 of Spades' , value:4 , img: '4S.png'},
  {name:'4 of Hearts' , value:4 , img: '4H.png'},
  {name:'5 of Clubs' , value:5 , img: '5C.png'},
  {name:'5 of Diamonds' , value:5 , img: '5D.png'},
  {name:'5 of Spades' , value:5 , img: '5S.png'},
  {name:'5 of Hearts' , value:5 , img: '5H.png'},
  {name:'6 of Clubs' , value:6, img: '6C.png'},
  {name:'6 of Diamonds' , value:6 , img: '6D.png'},
  {name:'6 of Spades' , value:6 , img: '6S.png'},
  {name:'6 of Hearts' , value:6 , img: '6H.png'},
  {name:'7 of Clubs' , value:7, img: '7C.png'},
  {name:'7 of Diamonds' , value:7 , img: '7D.png'},
  {name:'7 of Spades' , value:7 , img: '7S.png'},
  {name:'7 of Hearts' , value:7 , img: '7H.png'},
  {name:'8 of Clubs' , value:8 , img: '8C.png'},
  {name:'8 of Diamonds' , value:8 , img: '8D.png'},
  {name:'8 of Spades' , value:8 , img: '8S.png'},
  {name:'8 of Hearts' , value:8 , img: '8H.png'},
  {name:'9 of Clubs' , value:9 , img: '9C.png'},
  {name:'9 of Diamonds' , value:9 , img: '9D.png'},
  {name:'9 of Spades' , value:9 , img: '9S.png'},
  {name:'9 of Hearts' , value:9 , img: '9H.png'},
  {name:'10 of Clubs' , value:10 , img: '10C.png'},
  {name:'10 of Diamonds' , value:10 , img: '10D.png'},
  {name:'10 of Spades' , value:10 , img: '10S.png'},
  {name:'10 of Hearts' , value:10 , img: '10H.png'},
  {name:'Jack of Clubs' , value:11 , img: 'JC.png'},
  {name:'Jack of Diamonds' , value:11 , img: 'JD.png'},
  {name:'Jack of Spades' , value:11 , img: 'JS.png'},
  {name:'Jack of Hearts' , value:11 , img: 'JH.png'},
  {name:'Queen of Clubs' , value:12 , img: 'QC.png'},
  {name:'Queen of Diamonds' , value:12 , img: 'QD.png'},
  {name:'Queen of Spades' , value:12 , img: 'QS.png'},
  {name:'Queen of Hearts' , value:12 , img: 'QH.png'},
  {name:'King of Clubs' , value:13 , img: 'KC.png'},
  {name:'King of Diamonds' , value:13 , img: 'KD.png'},
  {name:'King of Spades' , value:13 , img: 'KS.png'},
  {name:'King of Hearts' , value:13 , img: 'KH.png'},
  {name:'A\'s of Clubs' , value:14 , img: 'AC.png'},
  {name:'A\'s of Diamonds' , value:14 , img: 'AD.png'},
  {name:'A\'s of Spades' , value:14 , img: 'AS.png'},
  {name:'A\'s of Hearts' , value:14 , img: 'AH.png'},
  
]
cardBackground =[{name:'cardBackground' ,  img: 'cardBackgroundImg.png'}]
